### ISSUE TITLE
learn.lr()_find produces attribute error

### ISSUE THREAD

**Issue by randywreed** [morganmcg1/fasthugs#1]
I appreciate your effort to connect huggingface to fastai. However, when I run these lines, learn.lr_find() errors as below. I've made no changes to your code with the exception of the setup that I detailed below. I wonder if they've changed things to make your code incompatible.

`learn = Learner(dls, fasthugs_model, opt_func=opt_func, splitter=splitter, loss_func=loss, cbs=cbs, metrics=[accuracy])`
`learn.lr_find(show_plot=True)`

produces error:
AttributeError Traceback (most recent call last)
/content/fastai2/fastai2/learner.py in fit(self, n_epoch, lr, wd, cbs, reset_opt)
187 try:
--> 188 self._do_begin_fit(n_epoch)
189 for epoch in range(n_epoch):

26 frames
AttributeError: 'str' object has no attribute 'type'

During handling of the above exception, another exception occurred:

AttributeError Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/fastprogress/fastprogress.py in on_iter_end(self)
155 total_time = format_time(time.time() - self.main_bar.start_t)
156 self.text = f'Total time: {total_time}

' + self.text
--> 157 self.out.update(HTML(self.text))
158
159 def add_child(self, child):

AttributeError: 'NBMasterBar' object has no attribute 'out'

Run in Google Colab
Setup as specified elsewhere:
`!pip install transformers`
`!git clone https://github.com/fastai/fastai2`
`%cd fastai2`
`!pip install -e ".[dev]"`
`!pip uninstall --y fastprogress`
`!pip install git+https://github.com/fastai/fastprogress --upgrade`

I posted this to fastaiv2 issues, but got the following response:
"It's impossible to fix your problem without seeing the code you have executed. There is a problem when you try to train, that could come either from the data collection, the model, the loss function, the optimizer, and just giving the last line of the error message is not enough."

While I clearly didn't give "the last line of the error message" (this is undoubtedly just a standard response). It seems like they are indicating the problem may be in your code.

**Comment by rubensmau** [comment]
I found your work very useful to me, and also found the same error using Colab. Interesting that other fastai2 notebooks run perfectly on Colab. Maybe this is a problem related to transformers  vs  fastai widgets

**Comment by rubensmau** [comment]
Just discovered that if you install a previous version, it works :
!pip install fastai2==0.0.13

**Comment by morganmcg1** [comment]
Sorry I'm so late seeing this, hopefully it works now. Generally I've seen that error when your `fastcore` library needs to be updated. I've updated the notebooks since this issue so hopefully there shouldn't be any further issues :)
