### ISSUE TITLE
TypeError: __init__() got multiple values for argument 'transformer_tokenizer'

### ISSUE THREAD

**Issue by msakthiganesh** [morganmcg1/fasthugs#6]
Hi,

I am trying to run the fasthugs_seq_classification.ipynb notebook on Colab. 

fastai==2.2.5
transformers = 4.2.1
tokenizers==0.9.4

I get the error mentioned below when I try to run:

splits = ColSplitter()(df)
x_tfms = [attrgetter("text"), fastai_tokenizer, Numericalize(vocab=tokenizer_vocab_ls), SpecialClsTokens(tokenizer)]
dsets = Datasets(df, splits=splits, tfms=[x_tfms, [attrgetter("label"), Categorize()]], dl_type=SortedDL)

Error:

Process Process-1:
 0.00% [0/1000 00:00<00:00]
Traceback (most recent call last):
Process Process-2:
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/fastcore/parallel.py", line 118, in _f_pg
    for i,b in enumerate(obj(batch)): queue.put((start_idx+i,b))
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/dist-packages/fastai/text/core.py", line 136, in __call__
    return (L(o).map(self.post_f) for o in self.tok(maps(*self.rules, batch)))
  File "/usr/local/lib/python3.6/dist-packages/fastcore/parallel.py", line 118, in _f_pg
    for i,b in enumerate(obj(batch)): queue.put((start_idx+i,b))
TypeError: __init__() got multiple values for argument 'transformer_tokenizer'
  File "/usr/local/lib/python3.6/dist-packages/fastai/text/core.py", line 136, in __call__
    return (L(o).map(self.post_f) for o in self.tok(maps(*self.rules, batch)))
TypeError: __init__() got multiple values for argument 'transformer_tokenizer'

PS:
I had to make the below mentioned changes to reach till this step.

1.  Manually set max_seq_len = 256 to avoid the warning (not sure why this is happening..)
Original: 
fht=FastHugsTokenizer(transformer_tokenizer=tokenizer, model_name='roberta', max_seq_len= max_seq_len, 
                 pretrained=True, pair=False)
tokenized_text = next(fht(txt))

Modified: 

fht=FastHugsTokenizer(transformer_tokenizer=tokenizer, model_name='roberta', max_seq_len=256, 
                 pretrained=True, pair=False)
tokenized_text = next(fht(txt))

2. Removed add_prefix_space = True from do_tokenize function
Original:

def do_tokenize(self, o:str):
        """Returns tokenized text, adds prefix space if needed, limits the maximum sequence length"""
        if 'roberta' in model_name: tokens=self.tok.tokenize(o, add_prefix_space=True)[:self.max_seq_len-2]
        else: tokens = self.tok.tokenize(o)[:self.max_seq_len-2]
        return tokens
    def __call__(self, items): 
        for o in items: yield self.do_tokenize(o)

Modified:

def do_tokenize(self, o:str):
        """Returns tokenized text, adds prefix space if needed, limits the maximum sequence length"""
        if 'roberta' in model_name: tokens=self.tok.tokenize(o)[:self.max_seq_len-2]
        else: tokens = self.tok.tokenize(o)[:self.max_seq_len-2]
        return tokens
    def __call__(self, items): 
        for o in items: yield self.do_tokenize(o)

3. Removed res_col_name, post_rules and renamed tok_func to Tok
Original:

fastai_tokenizer = Tokenizer.from_df(text_cols='text', res_col_name='text', tok_func=fasthugstok, 
                                     rules=[], post_rules=[])

Modified:

fastai_tokenizer = Tokenizer.from_df(text_cols='text', tok=fasthugstok, 
                                     rules=[])

Thanks in advance! :)

**Comment by PyaeHlianMoe** [comment]
Hi @msakthi19 , you can take a look at this [comment](https://forums.fast.ai/t/fasthugs-fastai-v2-and-huggingface-transformers/63681/49) in order to work with the new fastai. But need to use the specific versions in order to work.

**Comment by msakthiganesh** [comment]
Hi @PyaeHlianMoe ! Thanks a lot! I will try it out and update here :)
